name: Publish Workshop Material
on:
  push:
    branches:
      - main
jobs:
  create-archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ⚡ Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-cargo

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2

      - name: Install mdbook-admonish
        uses: baptiste0928/cargo-install@v3
        with:
          crate: mdbook-admonish

      - name: Build artifact
        run: make all

      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          files: workshop-material.tar.gz
